name: CD Development

on:
  workflow_run:
    workflows: ["CI", "CD Core Infrastructure Development"]
    branches: [main]
    types: [completed]

env:
  VERSION: ${{ github.sha }}
  APP_NAME: ${{ vars.APP_NAME }}
  ENVIRONMENT: development

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    name: build-artifact
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ vars.CONTAINER_REPO }}/${{ vars.APP_NAME }}:latest-dev

  deploy:
    needs: build-artifact
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .infra/terraform/${{ vars.APP_NAME }}-app
    name: deploy-package
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Config Terraform plugin cache
        run: |
          echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
          mkdir --parents ~/.terraform.d/plugin-cache

      - name: Terraform Cache
        uses: actions/cache@v3
        env:
          cache-name: tf-cache
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: tf-build-${{ vars.APP_NAME }}-${{ env.cache-name }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            tf-build-${{ vars.APP_NAME }}-${{ env.cache-name }}-
            tf-build-${{ vars.APP_NAME }}-

      - name: Terraform init
        id: init
        run: terraform init -backend-config environments/${{ env.ENVIRONMENT }}/config.s3.tfbackend

      - name: Run Terraform plan
        id: plan
        run: terraform plan -var-file environments/${{ env.ENVIRONMENT }}/terraform.tfvars -out ./plan.out -no-color

      - name: Terraform apply
        id: tf-apply
        run: terraform apply ./plan.out
