name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  VERSION: ${{ github.sha }}
  APP_NAME: ${{ vars.APP_NAME }}
  ENVIRONMENT: develop

jobs:
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: run-linter
        run: make golangci-lint
